pipeline {
    agent any

    environment { 
        dockerhub = credentials('docker-cred')
    }

    stages {
        stage('Build') {
            steps {
                sh "docker build -t image-purchase:latest ."
            }
        }

        stage('Login to Docker Hub') {
            steps {
                sh "echo passwordh | docker login -u hadhemidhifaoui --password-stdin"
            }
        }

        stage('Tag') {
            steps {
                sh "docker tag image-purchase:latest hadhemidhifaoui/image-purchase:latest"
            }
        }

        stage('Push to Docker Hub') {
            steps {
                sh "docker push hadhemidhifaoui/image-purchase:latest"
            }
        }
        stage('Run Docker Compose') {
            steps {
                sh 'docker-compose up -d'
            }
    }
}
