pipeline {
    agent any

    environment { 
        dockerhub = credentials('dockerhub')
    }

    stages {
        stage('Build') {
            steps {
                sh "docker build -t image-purchase:latest ."
            }
        }

        stage('Login to Docker Hub') {
            steps {
                sh "echo \${dockerhub_PSW} | docker login -u \${dockerhub_USR} --password-stdin"
            }
        }

        stage('Tag') {
            steps {
                sh "docker tag image-purchase:latest hadhemidhifaoui/image-purchase:latest"
            }
        }

        stage('Push to Docker Hub') {
            steps {
                sh "docker push hadhemidhifaoui/image-purchase:latest"
            }
        }
    }
}
