pipeline {
    agent any

    environment { 
        dockerhub = credentials('docker-cred')
    }

    stages {
          stage('Maven Install') {
            steps {
                script {
                    // Run Maven install
                    sh 'mvn clean install'
                }
            }
        }
        stage('Build') {
            steps {
                sh "docker build -t image-eureka:latest ."
            }
        }

        stage('Login to Docker Hub') {
            steps {
                sh "echo passwordh | docker login -u hadhemidhifaoui --password-stdin"
            }
        }

        stage('Tag') {
            steps {
                sh "docker tag image-eureka:latest hadhemidhifaoui/image-eureka:latest"
            }
        }

        stage('Push to Docker Hub') {
            steps {
                sh "docker push hadhemidhifaoui/image-eureka:latest"
            }
        }
        stage('Run Docker Compose') {
            steps {
                sh 'docker-compose up -d'
            }
        }
    }
}
